markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Carlos Becker
production_url : http://caarlos0.github.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: caarlos0blog
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Carlos Alexandro Becker
  github : caarlos0
  twitter : caarlos0
